import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Typewriter from 'typewriter-effect';
import { motion as m } from 'framer-motion';

export default function Home() {
  return (
    <m.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.75, ease: "easeInOut" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.home}>
            <p>Hello, I am Jordan Nguyen</p>
            <hr className={styles.line}></hr>
            <div className={styles.me}>
              <p className={styles.passionate}>Passionate&nbsp;</p>
              <h2 className={styles.position}>
                <Typewriter options={{ strings: ["Web Developer", "UI/UX Designer"], autoStart: true, loop: true }} />
              </h2>
            </div>
            <button className={styles.button}>
              <h2>Get in Touch</h2>
            </button>
          </div>
          <div className={styles.placeholder}></div>
        </div>
      </main>
    </m.div>
  );
}

